server:
  port: 10010
spring:
  application:
    name: apigateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 3c7fbd2c-e4e5-4d0e-a2bb-366c865fee33
      config:
        namespace: 3c7fbd2c-e4e5-4d0e-a2bb-366c865fee33
    gateway:
      routes: # 路由规则
        - id: orderservice # 路由规则id，自定义，唯一
          uri: lb://apiservice # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/order/**
        - id: userservice # 路由规则id，自定义，唯一
          uri: lb://userservice # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG